services:
  backend:
    build: ./backend  # Uses backend/Dockerfile
    ports:
      - "8000:8000" # map host port 8000 to container port 8000
    
  # frontend:
  #   build: ./frontend  # Uses frontend/Dockerfile
